aerosol_data aero_data.dat
emission_data emissions.json
gas_data gas_data.dat
grid_name us4-cares
case_name cares 
dir_path /data/nriemer/a/jcurtis2/wrf_partmc/emissions/smoke_data/
start_date 20100618 
n_days_per_file 1
n_days 2 
do_point yes 
do_nonpoint no 
do_ag no 
do_rwc no 
do_nonroad no 
do_rail no 
do_mobile no 
do_bio no 
dx 4000.0
nx 169
ny 159 
nz 1
nt 49 
output_prefix cares_emissions_json/aero_emit_dists_
only_sectional no 
